name: tests
# Since this package must be tested inside a Laravel application this workflow does the following:
# Create a fresh Laravel host app
# Checkout package into host/packages/Ajthinking/Archetype
# Add the package in host composer.json repositories section
# Require the package using @dev
# Publishing config
# Running tests: vendor/phpunit/phpunit/phpunit packages/Ajthinking/Archetype/tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install host app
      run: composer create-project --prefer-dist laravel/laravel host
      
    - name: Checkout the package
      uses: actions/checkout@v2
      with:
        path: host/packages/Ajthinking/Archetype

    - name: Add composer.json repository
      working-directory: ./host      
      run: composer config repositories.archetype path "/home/runner/work/archetype/archetype/host/packages/Ajthinking/Archetype"

    - name: Require the package
      working-directory: ./host
      run: composer require ajthinking/archetype @dev

    - name: Run tests
      working-directory: ./host      
      run: vendor/phpunit/phpunit/phpunit packages/Ajthinking/Archetype/tests
